
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Aug 13 20:13:04 CST 2021
//----------------------------------------------------

package tarea5;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int COMA = 13;
  public static final int INTEGER = 11;
  public static final int PROGRAMA = 5;
  public static final int PUNTO_COMA = 7;
  public static final int P_C = 3;
  public static final int EOF = 0;
  public static final int P_A = 2;
  public static final int NUMERO = 14;
  public static final int ID = 4;
  public static final int IGUAL = 12;
  public static final int error = 1;
  public static final int PROCEDIMIENTO = 6;
  public static final int DOS_PUNTOS = 10;
  public static final int BEGIN = 9;
  public static final int END = 8;
  public static final int PARAMETRO = 15;
}

